{% set name = "fastapi-cli" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fastapi_cli-{{ version }}.tar.gz
  sha256: e2e9ffaffc1f7767f488d6da34b6f5a377751c996f397902eb6abb99a67bde32

build:
  entry_points:
    - fastapi = fastapi_cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-backend
    - pip
  run:
    - python >=3.8
    - typer >=0.12.3
    - fastapi
    - uvicorn >=0.15.0

test:
  imports:
    - fastapi_cli
  commands:
    - pip check
    - fastapi --help
  requires:
    - pip

about:
  home: https://github.com/tiangolo/fastapi-cli
  summary: Run and manage FastAPI apps from the command line with FastAPI CLI. 🚀
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
