{% set name = "fastapi-cli" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastapi_cli-{{ version }}.tar.gz
  sha256: 85a93df72ff834c3d2a356164512cabaf8f093d50eddad9309065a9c9ac5193a

build:
  entry_points:
    - fastapi = fastapi_cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - uvicorn >=0.15.0
    - rich-toolkit >=0.14.8
    - python >={{ python_min }}
    - typer >=0.15.1
    - uvicorn-standard >=0.15.0

test:
  imports:
    - fastapi_cli
  commands:
    - pip check
    - fastapi --help
  requires:
    - pip
    - fastapi
    - python {{ python_min }}

about:
  home: https://github.com/tiangolo/fastapi-cli
  summary: Run and manage FastAPI apps from the command line with FastAPI CLI. 🚀
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
