{% set name = "fastapi-cli" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastapi_cli-{{ version }}.tar.gz
  sha256: 02b3b65956f526412515907a0793c9094abd4bfb5457b389f645b0ea6ba3605e

build:
  entry_points:
    - fastapi = fastapi_cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - uvicorn >=0.15.0
    - rich-toolkit >=0.11.1
    - python >={{ python_min }}
    - typer >=0.12.3
    - uvicorn-standard >=0.15.0

test:
  imports:
    - fastapi_cli
  commands:
    - pip check
    - fastapi --help
  requires:
    - pip
    - fastapi
    - python {{ python_min }}

about:
  home: https://github.com/tiangolo/fastapi-cli
  summary: Run and manage FastAPI apps from the command line with FastAPI CLI. 🚀
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
