schema_version: 1

context:
  name: fastapi-cli
  version: "0.0.27"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fastapi_cli-${{ version }}.tar.gz
  sha256: 1dffb1e40c0c88f2e0171a8a252a2b615c1e63ff8c05626649e4badd6a84336a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fastapi = fastapi_cli.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - rich-toolkit >=0.14.8
    - tomli >=2.0.0
    - typer >=0.16
    - uvicorn-standard >=0.15.0
tests:
  - python:
      imports:
        - fastapi_cli
  - requirements:
      run:
        - fastapi
        - python ${{ python_min }}.*
    script:
      - fastapi --help

about:
  summary: Run and manage FastAPI apps from the command line with FastAPI CLI. 🚀
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tiangolo/fastapi-cli

extra:
  recipe-maintainers:
    - synapticarbors
