schema_version: 1

context:
  name: fastapi-cli
  version: 0.0.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fastapi_cli-${{ version }}.tar.gz
  sha256: 85a93df72ff834c3d2a356164512cabaf8f093d50eddad9309065a9c9ac5193a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - fastapi = fastapi_cli.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - rich-toolkit >=0.14.8
    - typer >=0.15.1
    - uvicorn-standard >=0.15.0

tests:
  - python:
      imports:
        - fastapi_cli
  - requirements:
      run:
        - fastapi
        - python ${{ python_min }}.*
    script:
      - fastapi --help

about:
  summary: Run and manage FastAPI apps from the command line with FastAPI CLI. 🚀
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tiangolo/fastapi-cli

extra:
  recipe-maintainers:
    - synapticarbors
